name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy React app to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
            